packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.83
    '@iconify-json/simple-icons': ^1.2.65
    '@nuxt/content': ^3.10.0
    '@nuxt/devtools': ^3.1.1
    '@nuxt/image': ^1.11.0
    '@nuxt/scripts': ^0.13.2
    '@nuxtjs/i18n': ^10.2.1
    '@nuxtjs/seo': ^3.3.0
    bumpp: ^10.3.2
    dotenv: ^17.2.3
    eslint: ^9.39.2
    husky: ^9.1.7
    lint-staged: ^16.2.7
    nitropack: ^2.13.0
    nuxt: ^4.2.2
    nuxt-auth-utils: ^0.5.26
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    vite: ^7.3.1
    vue-tsc: ^3.2.2
  integrations:
    '@date-fns/tz': ^1.4.1
    '@neoconfetti/vue': ^2.2.1
    '@nextorders/avatar': ^1.0.3
    '@nuxt/ui': ^4.3.0
    '@paralleldrive/cuid2': 2.3.1
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^14.1.0
    '@vueuse/nuxt': ^14.1.0
    aws4fetch: ^1.0.20
    grammy: ^1.39.2
    ioredis: ^5.9.1
    libphonenumber-js: ^1.12.33
    pinia: ^3.0.4
    zod: ^4.3.5
  test:
    '@vitest/browser-playwright': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    playwright: ^1.57.0
    vitest: ^4.0.16
    vitest-browser-vue: ^2.0.1
  types:
    '@types/node': ^24.10.6

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

shamefullyHoist: true
