packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.70
    '@iconify-json/simple-icons': ^1.2.54
    '@nuxt/content': ^3.7.1
    '@nuxt/devtools': ^2.6.5
    '@nuxt/image': ^1.11.0
    '@nuxt/scripts': ^0.13.0
    '@nuxtjs/i18n': ^10.1.1
    '@nuxtjs/seo': ^3.2.2
    bumpp: ^10.3.1
    dotenv: ^17.2.3
    drizzle-kit: ^0.31.5
    eslint: ^9.38.0
    husky: ^9.1.7
    lint-staged: ^16.2.4
    nitropack: ^2.12.7
    nuxt: ^4.1.3
    nuxt-auth-utils: ^0.5.25
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    vite: ^7.1.10
    vite-tsconfig-paths: ^5.1.4
    vue-tsc: ^3.1.1
  integrations:
    '@date-fns/tz': ^1.4.1
    '@neoconfetti/vue': ^2.2.1
    '@nextorders/avatar': ^1.0.3
    '@nuxt/ui': ^4.0.1
    '@paralleldrive/cuid2': ^2.2.2
    '@pinia/nuxt': ^0.11.2
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    aws4fetch: ^1.0.20
    drizzle-cuid2: ^2.1.0
    drizzle-orm: ^0.44.6
    grammy: ^1.38.3
    ioredis: ^5.8.1
    libphonenumber-js: ^1.12.24
    pg: ^8.16.3
    pinia: ^3.0.3
    zod: ^4.1.12
  test:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    playwright: ^1.56.1
    vitest: ^3.2.4
    vitest-browser-vue: ^1.1.0
  types:
    '@types/node': ^24.8.1
    '@types/pg': ^8.15.5

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

shamefullyHoist: true
