packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.71
    '@iconify-json/simple-icons': ^1.2.56
    '@nuxt/content': ^3.8.0
    '@nuxt/devtools': ^3.0.1
    '@nuxt/image': ^1.11.0
    '@nuxt/scripts': ^0.13.0
    '@nuxtjs/i18n': ^10.1.2
    '@nuxtjs/seo': ^3.2.2
    bumpp: ^10.3.1
    dotenv: ^17.2.3
    eslint: ^9.39.0
    husky: ^9.1.7
    lint-staged: ^16.2.6
    nitropack: ^2.12.9
    nuxt: ^4.2.0
    nuxt-auth-utils: ^0.5.25
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    vite: ^7.1.12
    vue-tsc: ^3.1.2
  integrations:
    '@date-fns/tz': ^1.4.1
    '@neoconfetti/vue': ^2.2.1
    '@nextorders/avatar': ^1.0.3
    '@nuxt/ui': ^4.1.0
    '@paralleldrive/cuid2': 2.2.2
    '@pinia/nuxt': ^0.11.2
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    aws4fetch: ^1.0.20
    grammy: ^1.38.3
    ioredis: ^5.8.2
    libphonenumber-js: ^1.12.25
    pinia: ^3.0.3
    zod: ^4.1.12
  test:
    '@vitest/browser-playwright': ^4.0.6
    '@vitest/coverage-v8': ^4.0.6
    playwright: ^1.56.1
    vitest: ^4.0.6
    vitest-browser-vue: ^2.0.1
  types:
    '@types/node': ^24.9.2

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

shamefullyHoist: true
