packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^5.4.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@date-fns/tz': ^1.4.1
  '@dicebear/collection': ^9.2.4
  '@dicebear/core': ^9.2.4
  '@iconify-json/circle-flags': ^1.2.8
  '@iconify-json/fluent-emoji-flat': ^1.2.5
  '@iconify-json/lucide': ^1.2.68
  '@iconify-json/simple-icons': ^1.2.52
  '@neoconfetti/vue': ^2.2.1
  '@nuxt/content': ^3.7.1
  '@nuxt/devtools': ^2.6.5
  '@nuxt/image': ^1.11.0
  '@nuxt/scripts': ^0.11.13
  '@nuxt/ui': ^3.3.4
  '@nuxtjs/i18n': ^10.1.0
  '@nuxtjs/seo': ^3.2.2
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': ^0.11.2
  '@types/node': ^24.5.2
  '@types/pg': ^8.15.5
  '@unhead/vue': ^2.0.17
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vueuse/core': ^13.9.0
  '@vueuse/nuxt': ^13.9.0
  aws4fetch: ^1.0.20
  changelogen-monorepo: ^0.5.0
  dotenv: ^17.2.2
  drizzle-cuid2: ^2.1.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  eslint: ^9.36.0
  grammy: ^1.38.2
  husky: ^9.1.7
  ioredis: ^5.7.0
  libphonenumber-js: ^1.12.17
  lint-staged: ^16.1.6
  nuxt: ^4.1.2
  nuxt-auth-utils: ^0.5.25
  nuxt-tiptap-editor: ^2.3.1
  nuxt-zod-i18n: ^1.12.1
  pg: ^8.16.3
  pinia: ^3.0.3
  playwright: ^1.55.0
  typescript: ^5.9.2
  unbuild: ^3.6.1
  vite: ^7.1.7
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vitest-browser-vue: ^1.1.0
  vue-tsc: ^3.0.7
  zod: ^3.25.76
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
  - sharp
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
