name: Trigger Release

on:
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        run: pnpm run release
